feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: phoenix14
# dataset: phoenix14-si5
num_epoch: 80
work_dir: ./work_dir/baseline_res18/
batch_size: 2
random_seed: 0
test_batch_size: 8
num_worker: 10
device: 0,1,2
log_interval: 50
eval_interval: 1
save_interval: 5
# python in default
evaluate_tool: python

loss_weights:
  ConvCTC: 1.0
  SeqCTC: 1.0
  Dist: 25.0
  recognition_loss_weight: 1.0
  translation_loss_weight: 1.0
# load_weights: ./slt_baseresline/baseline_p14_framewise_biCTC/dev_21.90_epoch55_model.pt

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  step: [ 40, 60]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0

model: slt_vac.SLTVACModel
decode_mode: beam

model_args:
  num_classes: 1296
  c2d_type: resnet18
  conv_type: 2
  use_bn: 1

initializer:
  initializer: xavier
  bias_initializer: zeros
  init_gain: 1.0
  embed_initializer: xavier
  embed_init_gain: 1.0
  tied_softmax: false

encoder:
  type: transformer
  num_layers: 3
  num_heads: 8
  embeddings:
      embedding_dim: 512
      scale: false
      dropout: 0.1
      norm_type: batch
      activation_type: softsign
  hidden_size: 512
  ff_size: 2048
  dropout: 0.1

decoder:
  type: transformer
  num_layers: 3
  num_heads: 8
  embeddings:
      embedding_dim: 512
      scale: false
      dropout: 0.1
      norm_type: batch
      activation_type: softsign
  hidden_size: 512
  ff_size: 2048
  dropout: 0.1
